# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

require 'getoptlong'
opts = GetoptLong.new(
        [ '--vm_mem',             GetoptLong::OPTIONAL_ARGUMENT ],
        [ '--trustrap_role',      GetoptLong::REQUIRED_ARGUMENT ],
        [ '--trustrap_env',       GetoptLong::REQUIRED_ARGUMENT ],
        [ '--trustrap_repouser',  GetoptLong::OPTIONAL_ARGUMENT ],
        [ '--trustrap_reponame',  GetoptLong::OPTIONAL_ARGUMENT ],
        [ '--trustrap_repobranch',GetoptLong::OPTIONAL_ARGUMENT ]
)

# process args
vm_mem =2048
trustrap_role = 'base'
trustrap_env  = 'dev'
trustrap_repouser   = 'pauldavidgilligan-msm'
trustrap_reponame   = 'msm-provisioning'
trustrap_repobranch = 'handsome-vagrant-docker'

opts.each do |opt, arg|
 case opt
   when '--vm_mem'
    vm_mem = arg
   when '--trustrap_role'
    trustrap_role = arg
   when '--trustrap_env'
    trustrap_env = arg
   when '--trustrap_repouser'
    trustrap_repouser = arg
   when '--trustrap_reponame'
    trustrap_reponame = arg
   when '--trustrap_repobranch'
    trustrap_repobranch = arg
 end
end

puts "-" * 40
puts "vm_mem              #{vm_mem}"
puts "-" * 40
puts "trustrap_role       #{trustrap_role}"
puts "trustrap_env        #{trustrap_env}"
puts "trustrap_repouser   #{trustrap_repouser}"
puts "trustrap_reponame   #{trustrap_reponame}"
puts "trustrap_repobranch #{trustrap_repobranch}"
puts "=" * 40

trustrap_args = "--role #{trustrap_role} --environment #{trustrap_env} --repouser #{trustrap_repouser} --reponame #{trustrap_reponame} --repobranch #{trustrap_repobranch}"
trustrap_tag = "#{trustrap_env}-#{trustrap_role}"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.username = "dev-opts"
  config.ssh.pty = true
  config.vm.define "#{trustrap_tag}" do |m|
    m.vm.provider "docker" do |d|
      d.build_dir = "."
      d.build_args = ["--tag=msm-#{trustrap_tag}"]
      d.remains_running = false
      d.has_ssh = true
      d.vagrant_machine = "dockerhost"
      d.vagrant_vagrantfile = "../Vagrantfile.proxy"
    end
  end 
  config.vm.provision :shell, :path => "../../../init.sh", :args => trustrap_args
# config.vm.provision :shell, inline: "echo Hello, World"
end


