# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

VAGRANTFILE_API_VERSION = "2"

require 'getoptlong'
opts = GetoptLong.new(
        [ '--TRUSTRAP_SERVICE',   GetoptLong::REQUIRED_ARGUMENT ],
        [ '--TRUSTRAP_ENV',       GetoptLong::REQUIRED_ARGUMENT ],
        [ '--TRUSTRAP_REPOUSER',  GetoptLong::OPTIONAL_ARGUMENT ],
        [ '--TRUSTRAP_REPONAME',  GetoptLong::OPTIONAL_ARGUMENT ],
        [ '--TRUSTRAP_REPOBRANCH',GetoptLong::OPTIONAL_ARGUMENT ]
)

# process args
TRUSTRAP_SERVICE = 'agg'
TRUSTRAP_ENV = 'dev'
TRUSTRAP_REPOUSER   = 'pauldavidgilligan-msm'
TRUSTRAP_REPONAME   = 'msm-provisioning'
TRUSTRAP_REPOBRANCH = 'handsome-vagrant-docker'

opts.each do |opt, arg|
 case opt
   when '--TRUSTRAP_SERVICE'
    TRUSTRAP_SERVICE = arg
   when '--TRUSTRAP_ENV'
    TRUSTRAP_ENV = arg
   when '--TRUSTRAP_REPOUSER'
    TRUSTRAP_REPOUSER = arg
   when '--TRUSTRAP_REPONAME'
    TRUSTRAP_REPONAME = arg
   when '--TRUSTRAP_REPOBRANCH'
    TRUSTRAP_REPOBRANCH = arg
 end
end

puts "-" * 40
puts "TRUSTRAP, vagrant docker provisioning"
puts "-" * 40
puts "TRUSTRAP_SERVICE    #{TRUSTRAP_SERVICE}"
puts "TRUSTRAP_ENV        #{TRUSTRAP_ENV}"
puts "TRUSTRAP_REPOUSER   #{TRUSTRAP_REPOUSER}"
puts "TRUSTRAP_REPONAME   #{TRUSTRAP_REPONAME}"
puts "TRUSTRAP_REPOBRANCH #{TRUSTRAP_REPOBRANCH}"
puts "=" * 40

# this is made to be somewhat backwards compatible.
# ./init.sh -s agg -e dev -u pauldavidgilligan-msm -n msm-provisioning -b handsome-vagrant-docker
TRUSTRAP_args = "-s #{TRUSTRAP_SERVICE} -e #{TRUSTRAP_ENV} -u #{TRUSTRAP_REPOUSER} -n #{TRUSTRAP_REPONAME} -b #{TRUSTRAP_REPOBRANCH}"
TRUSTRAP_tag = "#{TRUSTRAP_ENV}-#{TRUSTRAP_SERVICE}"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.username = "dev-opts"
  config.ssh.pty = true
  config.vm.define "#{TRUSTRAP_tag}" do |m|
    m.vm.provider "docker" do |d|
      d.has_ssh = true
      d.build_dir = "."
      d.build_args = ["--tag=msm-#{TRUSTRAP_tag}"]
      d.create_args = ["--dns=8.8.8.8", "--dns=4.4.4.4"]
      d.vagrant_machine = "dockerhost"
      d.vagrant_vagrantfile = "../Vagrantfile.proxy"
    end
  end 
  config.vm.provision :shell, :path => "../../../init.sh", :args => TRUSTRAP_args
end


