# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Vagrantfile   Provision MSM/TSM trustrap services.
#
# Authors:      Paul Gilligan, <Paul.Gilligan@moneysupermarket.com>
#
# Description:  This is a multi-host docker provider provisioning Vagrantfile.
#

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

VAGRANTFILE_API_VERSION = "2"

# -----------------------------------------------------------------------------
# Provision 
# -----------------------------------------------------------------------------
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.username = "dev-opts"
  config.ssh.pty = true
  config.ssh.forward_agent = true

  config.vm.define "nginx-ssl" do |m|
    m.vm.provider "docker" do |vm|
      vm.name            = "nginx-ssl"
      vm.has_ssh         = true
      vm.build_dir = "."
      vm.build_args = ["--tag=sp7829/nginx-ssl"]
      vm.create_args     = ["--privileged", "--dns=8.8.8.8", "--dns=4.4.4.4"]
      vm.vagrant_machine = "dockerhost"
      vm.vagrant_vagrantfile = "../Vagrantfile.proxy"
    end
  end
end

