services:
  hvd-agg:
    - nameserver: 10.10.3.30
    - domain: msm.internal
    - fe-domain: fe.msm.internal
    - be-domain: be.msm.internal
    - skydns: true
    - ejbca: false
    - tango: true
    - git:
      - reponame   : msm-provisioning
      - repouser   : pauldavidgilligan-msm
      - repobranch : handsome-vagrant-docker
    - roles:
      - data                        : agg-mongodb
        alias                       : agg-mongodb1
        enabled                     : false
      - data                        : agg-lts-mongodb
        alias                       : agg-lts-mongodb1
        enabled                     : false
      - data                        : agg-redis
        alias                       : agg-redis1
        enabled                     : false
      - app                         : agg-management-agent
        alias                       : agg-management-agent1
        enabled                     : false
      - app                         : agg-private-api
        enabled                     : false
      - app                         : agg-public-api
        enabled                     : false
      - app                         : agg-performance-test-proxy
        enabled                     : false
      - app                         : agg_kafka
        enabled                     : false

