services:
  hvd-agg:
    - domain: msm.internal
    - skydns: true
    - git:
      - reponame   : msm-provisioning
      - repouser   : pauldavidgilligan-msm
      - repobranch : handsome-vagrant-docker
    - roles:
      - data                        : agg-mongodb
        alias                       : agg-mongodb1
        enabled                     : true
      - data                        : agg-lts-mongodb
        alias                       : agg-lts-mongodb1
        enabled                     : true
      - data                        : agg-redis
        alias                       : agg-redis1
        enabled                     : true
      - app                         : agg-management-agent
        alias                       : agg-management-agent1
        enabled                     : true
      - app                         : agg-private-api
        enabled                     : false
      - app                         : agg-public-api
        enabled                     : false
      - app                         : agg-performance-test-proxy
        enabled                     : false
      - app                         : agg_kafka
        enabled                     : false

